# -*- coding: utf-8 -*-
"""DA day-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txr5CXeG_iEwhCpMspJlCH0cNiwP0sbO
"""

import pandas as pd


data = {
    'customer_id': [101, 102, 103, 104, 105],
    'age': [25, 30, 35, 28, 40],
    'gender': ['Male', 'Female', 'Female', 'Male', 'Male'],
    'city': ['Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Pune'],
    'purchase_amount': [2000, 3000, 2500, 4000, 3500]
}


df = pd.DataFrame(data)

print(df)

import pandas as pd

data = [
    [101, 25, 'Male', 'Delhi', 2000],
    [102, 30, 'Female', 'Mumbai', 3000],
    [103, 35, 'Female', 'Chennai', 2500],
    [104, 28, 'Male', 'Kolkata', 4000],
    [105, 40, 'Male', 'Pune', 3500]
]

columns = ['customer_id', 'age', 'gender', 'city', 'purchase_amount']

df = pd.DataFrame(data, columns=columns)

print(df)

import pandas as pd

data = {
    'customer_id': [101, 102, 103, 104, 105],
    'age': [25, None, 35, 28, None],
    'purchase_amount': [2000, 3000, None, 4000, 3500]
}

df = pd.DataFrame(data)

print(df)

df.to_csv("customer_data.csv", index=False)

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler


data = pd.DataFrame({
    'Age': [20, 25, 30, 35, 40],
    'Salary': [20000, 25000, 30000, 35000, 40000]
})


scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

print("Min-Max Normalized Data:\n", data_scaled)

standard_scaler = StandardScaler()
data_standardized = standard_scaler.fit_transform(data)

print("\nStandard Scaled Data:\n", data_standardized)

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

data = pd.DataFrame({
    'Age': [20, 25, 30, 35, 40],
    'Salary': [20000, 25000, 30000, 35000, 40000]
})

# Min-Max Scaling
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

print("Min-Max Normalized Data:\n", data_scaled)